# Used to choose files to be encrypted by secrets encryption git hooks
# Actual encryption rules for SOPS are in regular .sops.yaml files in repository
# Only 'path_regex' rules are used by hooks
# The order of the rules does not matter; all the rules will be included in one pattern
# See README-secretsencrypton.md for more info
#
creation_rules:
  - path_regex: secrets/.*
  - path_regex: \.conf$
  - path_regex: \.cfg$
  - path_regex: \.yaml$
  - path_regex: ^\.env$
  - path_regex: \.ini$
  # - encrypted_regex: .*
